# Generated by Django 2.0.3 on 2018-05-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180509_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
