# Generated by Django 2.0.3 on 2018-05-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180510_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LanguageXML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.TextField()),
            ],
        ),
    ]
