# Generated by Django 2.0.3 on 2018-05-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180516_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='offset',
        ),
    ]
