# Generated by Django 2.0.6 on 2018-06-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
